---
### START - to be removed when upgrading to ood-ansible >4.0.1
# As suggested in https://github.com/OSC/ood-ansible/issues/283
#node_repo_key_id: "6F71F525282841EEDAF851B42F59B5F99B1BE0B4"

# Override repo URLs to use OOD 4.1 repository (ood-ansible v4.0.1 defaults to 4.0) - to be removed when upgrading to ood-ansible >4.0.1
#rpm_repo_url: "https://yum.osc.edu/ondemand/4.1/ondemand-release-web-4.1-1.{{ el_distro }}.noarch.rpm"
#apt_repo_url: "https://apt.osc.edu/ondemand/4.1/ondemand-release-web_4.1.0-{{ deb_distro }}_all.deb"
### END - to be removed when upgrading to ood-ansible >4.0.1

ood_apps:
  dashboard:
    env:
      ood_bc_dynamic_js: true

host_regex: '[^./]+'
node_uri: '/node'
rnode_uri: '/rnode'
pun_pre_hook_root_cmd: /etc/ood/config/pun_pre_hook.sh
cancel_session_enabled: true

pun_custom_env:
  OOD_DASHBOARD_TITLE: "Open OnDemand with Azure CycleCloud"
  OOD_BRAND_BG_COLOR: "#0078d4"
  OOD_BRAND_LINK_ACTIVE_BG_COLOR: "#212529"
  OOD_JOB_NAME_ILLEGAL_CHARS: "/"
  OOD_SHELL_PING_PONG: true

# See https://osc.github.io/ood-documentation/latest/customization.html#pinning-applications-to-the-dashboard
pinned_apps_group_by: category
pinned_apps:
  - sys/shell
  - category: 'Interactive Apps'
