---
- name: Allow httpd to make outbound network connections (required for OIDC)
  command: setsebool -P httpd_can_network_connect on
  changed_when: true

- name: Ensure apache is restarted
  service: 
    name: httpd
    state: restarted
    enabled: yes

